export const BINDER_ENDPOINTS = {
  binders: '/binders',
  binderById: (binderId: number | string) => `/binders/${binderId}`,
  binderReceiveMaterial: (binderId: number | string) => `/binders/${binderId}/receive-material`,
  binderMarkFull: (binderId: number | string) => `/binders/${binderId}/mark-full`,
  binderReopenCapacity: (binderId: number | string) => `/binders/${binderId}/reopen-capacity`,
  binderMarkReadyForHandover: (binderId: number | string) => `/binders/${binderId}/mark-ready-for-handover`,
  binderRevertReadyForHandover: (binderId: number | string) => `/binders/${binderId}/revert-ready-for-handover`,
  binderHandoverToClient: (binderId: number | string) => `/binders/${binderId}/handover-to-client`,
  binderMarkReadyForHandoverBulk: '/binders/mark-ready-for-handover-bulk',
  binderHandoverToClientBulk: '/binders/handover-to-client-bulk',
  binderReceive: '/binders/receive',
  binderHistory: (binderId: number | string) => `/binders/${binderId}/history`,
  binderIntakes: (binderId: number | string) => `/binders/${binderId}/intakes`,
  bindersOpen: '/binders/open',
  clientBinders: (clientId: number | string) => `/clients/${clientId}/binders`,
} as const
