export const ANNUAL_REPORT_ENDPOINTS = {
  list: '/annual-reports',
  byId: (id: number | string) => `/annual-reports/${id}`,
  transition: (id: number | string) => `/annual-reports/${id}/transition`,
  submit: (id: number | string) => `/annual-reports/${id}/submit`,
  status: (id: number | string) => `/annual-reports/${id}/status`,
  deadline: (id: number | string) => `/annual-reports/${id}/deadline`,
  schedules: (id: number | string) => `/annual-reports/${id}/schedules`,
  completeSchedules: (id: number | string) => `/annual-reports/${id}/schedules/complete`,
  audit: (id: number | string) => `/annual-reports/${id}/audit`,
  details: (id: number | string) => `/annual-reports/${id}/details`,
  amend: (id: number | string) => `/annual-reports/${id}/amend`,
  exportPdf: (id: number | string) => `/annual-reports/${id}/export/pdf`,
  financials: (id: number | string) => `/annual-reports/${id}/financials`,
  readiness: (id: number | string) => `/annual-reports/${id}/readiness`,
  taxCalculation: (id: number | string) => `/annual-reports/${id}/tax-calculation`,
  advancesSummary: (id: number | string) => `/annual-reports/${id}/advances-summary`,
  income: (id: number | string) => `/annual-reports/${id}/income`,
  incomeLine: (id: number | string, lineId: number | string) => `/annual-reports/${id}/income/${lineId}`,
  expenses: (id: number | string) => `/annual-reports/${id}/expenses`,
  expenseLine: (id: number | string, lineId: number | string) => `/annual-reports/${id}/expenses/${lineId}`,
  annex: (id: number | string, schedule: string) => `/annual-reports/${id}/annex/${schedule}`,
  annexLine: (id: number | string, schedule: string, lineId: number | string) =>
    `/annual-reports/${id}/annex/${schedule}/${lineId}`,
  overdue: '/annual-reports/overdue',
  clientReports: (clientId: number | string) => `/clients/${clientId}/annual-reports`,
  activeTaxYearSummary: '/tax-year/active/summary',
  activeTaxYearReports: '/tax-year/active/reports',
  defaultTaxYear: '/tax-year/default',
  taxYearSummary: (taxYear: number | string) => `/tax-year/${taxYear}/summary`,
  taxYearReports: (taxYear: number | string) => `/tax-year/${taxYear}/reports`,
  saveTaxCalculation: (id: number | string) => `/annual-reports/${id}/tax-calculation/save`,
  autoPopulate: (id: number | string) => `/annual-reports/${id}/auto-populate`,
  taxPreview: '/annual-reports/tax-preview',
} as const
