import type { EntityAuditType } from './api'
import { PAGE_SIZE_MD, PAGE_SIZE_MAX } from '@/constants/pagination.constants'

export const AUDIT_PAGE_SIZE = PAGE_SIZE_MD

export const AUDIT_USERS_LIST_PARAMS = { page: 1, page_size: PAGE_SIZE_MAX } as const

export const AUDIT_ACTION_LABELS: Record<string, string> = {
  created: 'נוצר',
  updated: 'עודכן',
  deleted: 'נמחק',
  restored: 'שוחזר',
  status_changed: 'שינוי סטטוס',
  issued: 'הונפק',
  paid: 'שולם',
  canceled: 'בוטל',
  income_added: 'נוספה הכנסה',
  income_updated: 'עודכנה הכנסה',
  income_deleted: 'נמחקה הכנסה',
  expense_added: 'נוספה הוצאה',
  expense_updated: 'עודכנה הוצאה',
  expense_deleted: 'נמחקה הוצאה',
  annual_report_detail_updated: 'עודכנו פרטי דוח',
  annual_report_deadline_updated: 'עודכן מועד הגשה',
  annex_line_added: 'נוספה שורת נספח',
  annex_line_updated: 'עודכנה שורת נספח',
  annex_line_deleted: 'נמחקה שורת נספח',
}

export const AUDIT_ACTIONS_BY_ENTITY_TYPE: Record<EntityAuditType, string[]> = {
  client: ['created', 'updated', 'deleted', 'restored'],
  business: ['created', 'updated', 'deleted', 'restored'],
  charge: ['created', 'updated', 'deleted', 'restored', 'issued', 'paid', 'canceled'],
  annual_report: [
    'created',
    'updated',
    'deleted',
    'restored',
    'status_changed',
    'annual_report_detail_updated',
    'annual_report_deadline_updated',
    'annex_line_added',
    'annex_line_updated',
    'annex_line_deleted',
    'income_added',
    'income_updated',
    'income_deleted',
    'expense_added',
    'expense_updated',
    'expense_deleted',
  ],
}

export const AUDIT_FIELD_LABELS: Record<string, string> = {
  full_name: 'שם לקוח',
  client_record_id: 'לקוח',
  client_type: 'סוג לקוח',
  id_number: 'מספר מזהה',
  entity_type: 'סוג ישות',
  business_name: 'שם עסק',
  business_id: 'עסק',
  office_client_number: 'מספר לקוח',
  status: 'סטטוס',
  amount: 'סכום',
  charge_type: 'סוג חיוב',
  category: 'קטגוריה',
  description: 'תיאור',
  form_type: 'סוג טופס',
  line_id: 'שורת דיווח',
  period: 'תקופה',
  months_covered: 'חודשים',
  source_type: 'סוג הכנסה',
  tax_year: 'שנת מס',
  vat_reporting_frequency: 'תדירות מע״מ',
  advance_payment_frequency: 'תדירות מקדמות',
  advance_rate: 'שיעור מקדמות',
  accountant_id: 'רואה חשבון',
  phone: 'טלפון',
  email: 'אימייל',
  address_street: 'רחוב',
  address_building_number: 'מספר בית',
  address_apartment: 'דירה',
  address_city: 'עיר',
  address_zip_code: 'מיקוד',
  opened_at: 'נפתח בתאריך',
  closed_at: 'נסגר בתאריך',
  issued_at: 'תאריך הנפקה',
  paid_at: 'תאריך תשלום',
  canceled_at: 'תאריך ביטול',
  cancellation_reason: 'סיבת ביטול',
  custom_deadline_note: 'הערת מועד מותאם',
  data: 'נתונים',
  deadline_type: 'סוג מועד',
  donation_amount: 'תרומות',
  filing_deadline: 'מועד הגשה',
  internal_notes: 'הערות פנימיות',
  line_number: 'מספר שורה',
  notes: 'הערות',
  schedule: 'נספח',
  annual_revenue: 'מחזור שנתי',
  advance_rate_updated_at: 'תאריך עדכון שיעור מקדמות',
}
